// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using JsonHandler;
//
//    var acmCode = AcmCode.FromJson(ACMCodes);

namespace AcmCodeJsonHandler
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AcmCode
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class AcmCode
    {
        public static AcmCode[] FromJson(string json) => JsonConvert.DeserializeObject<AcmCode[]>(json, JsonHandler.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this AcmCode[] self) => JsonConvert.SerializeObject(self, JsonHandler.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
